name: satellite-api
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2025.11.12
  - click=8.3.1
  - dnspython=2.8.0
  - email-validator=2.3.0
  - email_validator=2.3.0
  - exceptiongroup=1.3.1
  - expat=2.7.3
  - fastapi=0.128.0
  - fastapi-cli=0.0.20
  - fastapi-core=0.128.0
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.11
  - jinja2=3.1.6
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libuv=1.51.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - pthread-stubs=0.3
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.10.6
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - python=3.11.14
  - python-dotenv=1.2.1
  - python-multipart=0.0.21
  - python_abi=3.11
  - pyyaml=6.0.3
  - readline=8.3
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - setuptools=80.9.0
  - shellingham=1.5.4
  - sniffio=1.3.1
  - sqlite=3.51.0
  - starlette=0.50.0
  - tk=8.6.15
  - tomli=2.3.0
  - typer=0.21.0
  - typer-slim=0.21.0
  - typer-slim-standard=0.21.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - uvloop=0.22.1
  - watchfiles=1.1.1
  - websockets=15.0.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
prefix: /home/nbsmith/anaconda3/envs/satellite-api
